### ISSUE TITLE
Use SonarQube internal service 

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-tekton-tasks#12]
During the pipeline the sonarqube server should be access via internal kube service instead of external route/ingress

In crc the routes/ingress are https but self signed

```
ERROR: SonarQube server [https://sonarqube-tools.apps-crc.testing] can not be reached
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan INFO: ------------------------------------------------------------------------
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan INFO: EXECUTION FAILURE
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan INFO: ------------------------------------------------------------------------
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan INFO: Total time: 0.404s
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan INFO: Final Memory: 5M/303M
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan INFO: ------------------------------------------------------------------------
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan ERROR: Error during SonarQube Scanner execution
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarQube
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:85)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at java.base/java.security.AccessController.doPrivileged(Native Method)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:74)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:70)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:181)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:122)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.cli.Main.execute(Main.java:73)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
igc-nodejs-run-hft8d-test-bb6f9-pod-7kz5h step-sonar-scan Caused by: java.lang.IllegalStateException: Fail to get bootstrap index from server
```

**Comment by seansund** [comment]
Issue moved to [ibm-garage-cloud/planning #324](https://github.com/ibm-garage-cloud/planning/issues/324) via [**ZenHub**](https://www.zenhub.com/)
